### ISSUE TITLE
Custom game mode compatibility

### ISSUE THREAD

**Issue by TheRealNin** [Person8880/Shine#728]
Some custom game modes (combat, extermination, marine vs marine, siege, and various combinations of them) are compatible with some, if not most of the existing shine plugins. Would it be possible for a config or even the game mode/mod itself to specify which plugins are either explicitly compatible or incompatible?

Thanks!

**Comment by TheRealNin** [comment]
Cool! I had no idea Shine had this functionality. Where and when would I add such a hook? I cannot find any documentation on how to create shine hooks outside of plugins.

**Comment by TheRealNin** [comment]
Thanks!
I try that and it never seems to call my hook. Could you possibly post an example of exactly how I should be using this hook system?

**Comment by Person8880** [comment]
I'm assuming you were trying it with Combat? I've just released the update to remove the old checks for the standalone game which would have prevented it from being called.

**Comment by TheRealNin** [comment]
Thanks so much, but even with the latest update I still cannot get my `CanPluginLoad` hooks to get called.

**Comment by Person8880** [comment]
All I did to test was make a file with what I posted above, and added a file hook:
```lua
ModLoader.SetupFileHook( "lua/shine/core/shared/hook.lua", "lua/path/to/hook/script.lua", "post" )
```
Adding a print to the callback confirms it's called (though note that its currently called twice for any plugin with a `shared.lua` file and a `server.lua`/`client.lua` file).

**Comment by TheRealNin** [comment]
Amazing. I have never thought of using NS2's modloader to set up a hook with shine. I was under the impression that you couldn't do that for most files. I was instead attempting to create the hook elsewhere and I suppose it was happening too late in the load process.

Thanks again for your help!
