### ISSUE TITLE
AlwaysBlockFamilySharedPlayers Doesn’t appear to be working.

### ISSUE THREAD

**Issue by TA-Red** [Person8880/Shine#757]
I’ve got AlwaysBlockFamilySharedPlayers set to true, I’ve got CheckFamilySharing set to true, and I’ve got my API set as well. Verified with steam, redone twice, with the correct server IP assigned in the API. This setting appears not to be working.

Addendum: I’ve tried the steam API setting as just the IP, and http://iphere. I’ve also modified the firewall settings as well. I’m not sure what else there is I can do.

Is there anything I could be doing wrong here that would prevent the functionality from working?

**Comment by Person8880** [comment]
Apparently the code's been expecting the wrong response format all this time, so it treated every response as having no lender. 🤦‍♂️ 

I've just released a fix for this, but you'll need to delete the `config://shine/ExternalAPICache.json` file to make sure it doesn't re-use invalid cached responses.

**Comment by TA-Red** [comment]
I know I'm being a pest at this point, but it still doesn't seem to be working. I'm wondering if it's the ExternalAPICache.json itself.

The reason I say that is because I created a family shared account myself to test the functionality and it looks like according to the cache, it's reading the account as _not_ a family shared account.

`{
    "Steam": {
        "IsPlayingSharedGame": {
            "998785539": {
                "ExpiryTime": 1556216751,
                "Value": false
            }
        }
    }
}`


Above is the account I created, as well as how the cache is reading it (or I assume that's what's going on).

If I'm wrong about how it's being read, I apologize. I'm just very excited about this feature and want to do whatever I can to help get it working.

It just looks like, to the uneducated in code observer such as myself, that the family shared accounts aren't correctly being marked as family shared. Although I'm worried that this is a steam API issue, not a shine issue.

Either way, thanks!

**Comment by Person8880** [comment]
Is that after deleting the file? The cache is written to disk on map change (perhaps a bit unhelpful in this case), so deleting it without restarting the server entirely won't clear it.

**Comment by TA-Red** [comment]
Stopped server > Deleted file > restarted server

**Comment by Person8880** [comment]
Looks to me like Steam says they're not sharing the game. The response I get for that Steam ID is:
```json
{"response":{"lender_steamid":"0"}}
```

**Comment by TA-Red** [comment]
I guess that confirms it's a steam issue then. I created the account about two hours ago and went through all the family sharing steps, so there's no doubt in my mind now then that it's just steam reporting it incorrectly.

Well, I appreciate you looking into it and the time you've spent. I guess there's not much that can be done now. Either way though, thank you

**Comment by Person8880** [comment]
I found another problem with how the API call was being constructed, it was missing out a few parameters. Surprisingly, Steam doesn't indicate any error when they're missing, despite the fact it results in it always saying there's no lender.

There's also extra confusion as the API call only works if the player is actually playing the game at the time the call is made. If they're not playing, it returns 0 for the lender.

If you clear the cache and try again, hopefully this time it will work.

**Comment by TA-Red** [comment]
Confirmed working, now.

Awesome! Thanks for everything! I, and likely every single server op, really appreciate all the work you put into this. Thank you so much
